### ISSUE TITLE
Add an Console Icon on tabs bar

### ISSUE THREAD

**Issue by maxjf1** [alexeyvax/vscode-open-native-terminal#15]
Add an default open console icon on tabs bar (like the .run plugin icon).

Currently, is needed to click on the (...) icon to see the console option.

![image](https://user-images.githubusercontent.com/6114888/48901914-0c818d00-ee3e-11e8-8869-975330c25d1f.png)

![image](https://user-images.githubusercontent.com/6114888/48901970-3a66d180-ee3e-11e8-955c-cede901c45b4.png)

**Comment by alexeyvax** [comment]
Hi @maxjf1. Thank you for creating this issue.
I've already implemented it. I added one icon to tabs bar, which can open native terminal on the root folder by default. If you will need the button, which can open nt on the current folder, I'll add it for you.  Please let me know, Thanks :)

![selection_063](https://user-images.githubusercontent.com/22244018/50054699-93800780-0155-11e9-9e60-0ed2f5598931.png)

**Comment by maxjf1** [comment]
This is great, thanks!
