### ISSUE TITLE
Support iTerm for mac

### ISSUE THREAD

**Issue by belousovAV** [alexeyvax/vscode-open-native-terminal#17]
Thank you for this plugin.
Can you add terminal selection on macOs?

**Comment by alexeyvax** [comment]
Hi @belousovAV.
Thank you for creating this issue and that you use this extension.
I'm going to add this functionality during this week.
I let you know when this feature will be ready for usage.

**Comment by alexeyvax** [comment]
This feature with terminal for mac OS has been implemented and available since 1.6.0 version. @belousovAV can I ask you to check it on your mac and send feedback to me? Thanks.

**Comment by belousovAV** [comment]
Thanks for the quick response. Everything is working.
