### ISSUE TITLE
title bar icon drawing issue

### ISSUE THREAD

**Issue by takkyun** [alexeyvax/vscode-open-native-terminal#25]
As per the attached screenshots, the "open terminal" icon on the title bar is not drawn properly (although I am not entirely sure which is caused by this extension or app itself):

![Screen_Shot_2021-05-06_at_9_42_10_AM](https://user-images.githubusercontent.com/1464708/117291200-cd870b00-aec2-11eb-86ab-b2d078e4df91.png)

![Screen_Shot_2021-05-06_at_9_43_28_AM](https://user-images.githubusercontent.com/1464708/117291207-cfe96500-aec2-11eb-82eb-06378daef42e.png)

**Comment by takkyun** [comment]
It seems an issue with the VSCode app, not this extension.

It has been fixed in the following version:

```
Version: 1.57.0-insider
Commit: a19565da7dfc739fa26e36aae96113e19fe3806f
Date: 2021-05-07T18:11:54.098Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0
```

![image](https://user-images.githubusercontent.com/1464708/117528293-8feec300-b025-11eb-8995-7f5dd4a9c55b.png)

**Comment by lonix1** [comment]
I assume 1.57.0 comes out next month?
