### ISSUE TITLE
vscode settings

### ISSUE THREAD

**Issue by akaia-shadowfox** [alexeyvax/vscode-open-native-terminal#3]
Please add possibility for terminal path setup in vscode settings. I have i3 and use mate-terminal, extension can't work because orients only on gnome-terminal and konsole, mate-terminal is default terminal emulator, but x-terminal-emulator variant isn't working.

**Comment by alexeyvax** [comment]
Hi katecanaveral, I added possibility to setup default terminal in the settings.json (1.1.5v).
You can setup your terminal name to "open-native-terminal.use-default-terminal" rule.
Like this: "open-native-terminal.use-default-terminal": "mate-terminal"
I hope it will work fine for you. If you will have any issues please let me know.

**Comment by akaia-shadowfox** [comment]
Thank you, this is fine! I think I haven't questions anymore.
