### ISSUE TITLE
Would love the ability to open the native terminal from the project directory...

### ISSUE THREAD

**Issue by Fettabachi** [alexeyvax/vscode-open-native-terminal#7]
instead of doing `cd ..` from a child directory to get to it. Thanks for the extension.

**Comment by alexeyvax** [comment]
Good day @Fettabachi , Thank you for raising this issue. I have already implemented this functionality so you might be try this when you will update extension to 1.2.1 version.

![selection_041](https://user-images.githubusercontent.com/22244018/44945491-5cc6f100-adf3-11e8-8537-59b4f550b90c.png)

If you have any questions please let me know.
